export const RESET_BACKGROUND_COLOR = ''
export const DEFAULT_TOGGLED_BACKGROUND_COLOR = 'orange'
export const TOGGLE_EVENT_ON = 'toggleEventOn'
export const TOGGLE_EVENT_OFF = 'toggleEventOff'
export const ACTION_MESSAGE_SHOW_MODAL = 'showModal1234'
